### ISSUE TITLE
2 Questions

### ISSUE THREAD

**Issue by h0lmstr0m** [devoteam-g-cloud/apps-script#1]
First, this is exactly what I have been looking for, thank you so much for this.

My first question is, where are you supposed to paste the code? Is it in the script editor of the form?

Second question is, I keep getting the following error when running the Setup function, "ReferenceError: Calendar is not defined (line 77, file "Code")" It seems that it doesn't like my defined Calendar ID that I edited in the beginning variables. Do you have any examples of what the Calendar ID should actually look like?

**Comment by St3ph-fr** [comment]
Hi,

First thank you :-)

For the code you can paste it in a standalone script no need to use the script editor in form better for management.

For the error it is because you need to activate the adavanced google calendar service. Copy/paste the appsscript.json file in your script file (view >> show manifest file) or you can activate the advanced service (Resources >> Advanced Google Services).

Stéphane

**Comment by h0lmstr0m** [comment]
Stéphane,

Again, I cannot thank you enough. It is now working without a problem. Very huge help for a code noob.

Is there a best practice on keeping the script disabled if I ever need to? Guessing that I could just blank out the variables or make them intentionally wrong.

Also, can more than one of these run at a time? I assume so as long as the variables don't conflict, but I am unsure.

**Comment by St3ph-fr** [comment]
Hi

If you need to stop the script I added a function stopTrigger()
Just run it and it will delete the trigger and script will stop fired when an answer is added : https://github.com/devoteam-g-cloud/apps-script/blob/f6b917d6bc2aec51d34603f078c288d2b25bde8e/event-registration/code.js#L104

If yo uwant to run multiple form just copy paste the script file. You can have multiple script file with the same code that will fire for multiple form but you can't have 1 script that will fire for multiple form, it oculd be posisble but for this script not.

Stéphane

**Comment by St3ph-fr** [comment]
Hello

I added a function [stopApp](https://github.com/devoteam-g-cloud/apps-script/blob/5fee33038f2ea78e9834132fec2e06094573e0dd/event-registration/code.js#L30) 

you can delete the triggers setup for this script by just running the function.

Stéphane
